import { contextBridge, ipcRenderer } from 'electron';
import { IpcChannel, type IpcApi } from '../shared/ipc';

// Minimal, whitelisted bridge. contextIsolation is on and nodeIntegration is off,
// so the renderer only ever sees this typed `api` surface — nothing else.
const api: IpcApi = {
  ping: () => ipcRenderer.invoke(IpcChannel.ping),
  getWorkspaceState: () => ipcRenderer.invoke(IpcChannel.getWorkspaceState),
  pickWorkspaceFolder: () => ipcRenderer.invoke(IpcChannel.pickWorkspaceFolder),
  setWorkspaceFolder: (dir) => ipcRenderer.invoke(IpcChannel.setWorkspaceFolder, dir),
  revealWorkspace: () => ipcRenderer.invoke(IpcChannel.revealWorkspace),
  quitApp: () => ipcRenderer.invoke(IpcChannel.quitApp),
  getAiAccessStatus: () => ipcRenderer.invoke(IpcChannel.getAiAccessStatus),
  startAiAccess: (confirmFullRead) => ipcRenderer.invoke(IpcChannel.startAiAccess, confirmFullRead),
  stopAiAccess: () => ipcRenderer.invoke(IpcChannel.stopAiAccess),
  copyAiHttpConfig: () => ipcRenderer.invoke(IpcChannel.copyAiHttpConfig),
  getAiAccessSettings: () => ipcRenderer.invoke(IpcChannel.getAiAccessSettings),
  saveAiAccessSettings: (settings) => ipcRenderer.invoke(IpcChannel.saveAiAccessSettings, settings),
  resetAiAccessKey: () => ipcRenderer.invoke(IpcChannel.resetAiAccessKey),
  ingestImageEntry: (bytes) => ipcRenderer.invoke(IpcChannel.ingestImageEntry, bytes),
  listEntries: () => ipcRenderer.invoke(IpcChannel.listEntries),
  newEntry: () => ipcRenderer.invoke(IpcChannel.newEntry),
  storeImage: (bytes) => ipcRenderer.invoke(IpcChannel.storeImage, bytes),
  setEntryImage: (id, hash) => ipcRenderer.invoke(IpcChannel.setEntryImage, id, hash),
  deleteEntry: (id) => ipcRenderer.invoke(IpcChannel.deleteEntry, id),
  defineResultDimension: (dimension) => ipcRenderer.invoke(IpcChannel.defineResultDimension, dimension),
  listResultDimensions: () => ipcRenderer.invoke(IpcChannel.listResultDimensions),
  listResultVocabulary: () => ipcRenderer.invoke(IpcChannel.listResultVocabulary),
  deleteResultDimension: (id) => ipcRenderer.invoke(IpcChannel.deleteResultDimension, id),
  defineResultValue: (dimensionId, value, label) =>
    ipcRenderer.invoke(IpcChannel.defineResultValue, dimensionId, value, label),
  deleteResultValue: (dimensionId, value) => ipcRenderer.invoke(IpcChannel.deleteResultValue, dimensionId, value),
  restoreResultDimension: (id) => ipcRenderer.invoke(IpcChannel.restoreResultDimension, id),
  restoreResultValue: (dimensionId, value) => ipcRenderer.invoke(IpcChannel.restoreResultValue, dimensionId, value),
  listArchivedResults: () => ipcRenderer.invoke(IpcChannel.listArchivedResults),
  createEntry: (input) => ipcRenderer.invoke(IpcChannel.createEntry, input),
  updateEntry: (id, input) => ipcRenderer.invoke(IpcChannel.updateEntry, id, input),
  updateEntryCanvas: (id, canvasJson, annotations, thumbnail) =>
    ipcRenderer.invoke(IpcChannel.updateEntryCanvas, id, canvasJson, annotations, thumbnail),
  getEntry: (id) => ipcRenderer.invoke(IpcChannel.getEntry, id),
  setEntryTags: (id, tags) => ipcRenderer.invoke(IpcChannel.setEntryTags, id, tags),
  setEntryDate: (id, date) => ipcRenderer.invoke(IpcChannel.setEntryDate, id, date),
  queryAnnotationsByTag: (tag) => ipcRenderer.invoke(IpcChannel.queryAnnotationsByTag, tag),
  queryEntriesByTag: (tag) => ipcRenderer.invoke(IpcChannel.queryEntriesByTag, tag),
  locateAnnotation: (annotationId) => ipcRenderer.invoke(IpcChannel.locateAnnotation, annotationId),
  listGroups: () => ipcRenderer.invoke(IpcChannel.listGroups),
  defineGroup: (group) => ipcRenderer.invoke(IpcChannel.defineGroup, group),
  deleteGroup: (id) => ipcRenderer.invoke(IpcChannel.deleteGroup, id),
  defineValue: (value) => ipcRenderer.invoke(IpcChannel.defineValue, value),
  deleteValue: (groupId, value) => ipcRenderer.invoke(IpcChannel.deleteValue, groupId, value),
  restoreGroup: (id) => ipcRenderer.invoke(IpcChannel.restoreGroup, id),
  restoreValue: (groupId, value) => ipcRenderer.invoke(IpcChannel.restoreValue, groupId, value),
  purgeGroup: (id) => ipcRenderer.invoke(IpcChannel.purgeGroup, id),
  purgeValue: (groupId, value) => ipcRenderer.invoke(IpcChannel.purgeValue, groupId, value),
  listArchivedGroups: () => ipcRenderer.invoke(IpcChannel.listArchivedGroups),
  setGroupPinned: (id, pinned) => ipcRenderer.invoke(IpcChannel.setGroupPinned, id, pinned),
  reorderGroups: (ids) => ipcRenderer.invoke(IpcChannel.reorderGroups, ids),
  reorderValues: (groupId, values) => ipcRenderer.invoke(IpcChannel.reorderValues, groupId, values),
  getStampLibrary: () => ipcRenderer.invoke(IpcChannel.getStampLibrary),
  saveStampLibrary: (canvasJson) => ipcRenderer.invoke(IpcChannel.saveStampLibrary, canvasJson),
  runView: (query) => ipcRenderer.invoke(IpcChannel.runView, query),
  queryEntriesByView: (query) => ipcRenderer.invoke(IpcChannel.queryEntriesByView, query),
  countGroupValuesUnderView: (query, groupId) =>
    ipcRenderer.invoke(IpcChannel.countGroupValuesUnderView, query, groupId),
  distinctResultValues: (dimensionId) => ipcRenderer.invoke(IpcChannel.distinctResultValues, dimensionId),
  runStats: (query) => ipcRenderer.invoke(IpcChannel.runStats, query),
  queryStatsExamples: (query) => ipcRenderer.invoke(IpcChannel.queryStatsExamples, query),
  queryStatsScopeEntries: (scope) => ipcRenderer.invoke(IpcChannel.queryStatsScopeEntries, scope),
  createSavedView: (name, query) => ipcRenderer.invoke(IpcChannel.createSavedView, name, query),
  listSavedViews: () => ipcRenderer.invoke(IpcChannel.listSavedViews),
  getSavedView: (id) => ipcRenderer.invoke(IpcChannel.getSavedView, id),
  deleteSavedView: (id) => ipcRenderer.invoke(IpcChannel.deleteSavedView, id),
};

contextBridge.exposeInMainWorld('api', api);
